### PR TITLE
Rfc/issue 354 strict / SSG mode

### PR DESCRIPTION
**Pull request by thescientist13**
## Related Issue
in support of #354, introduces a "strict" mode that strips out all client side JavaScript for projects that don't need any "runtime" JavaScript

1. Introduced modes configuration option 
    - **ssg** - ships NO javascript (has some caveats)
    - **spa** - current behavior 
1. **spa** mode marks the `<script>` tag as `async`

Note this neat trick with [inline `<script>` tag](https://github.com/ProjectEvergreen/greenwood/pull/401)

> Posted some initial performance results [here](https://github.com/ProjectEvergreen/greenwood/pull/396#issuecomment-662150746).  In both cases, performance is improved, even if Greenwood website's performance score is low.  The hope is that enabling **progressive** mode could solve this, but probably an issue just for Lighthouse score should be ,ade.

## Questions
1. [x] Should we change the name to something other than mode, which [we might need for this](https://github.com/ProjectEvergreen/greenwood/issues/199)?
    - yes, will call it **optimization**

## TODO
1. [x] initial SPA benchmark / performance report
1. [x] rename **ssg** to **strict** mode (think of another name for **spa** mode?)
1. [x] Make ~~**strict**~~ **spa** mode default (the long term hope is that **progressive** mode would be the new default)
1. [x] Testing
    - [x]  **strict** as default for smoke test and test cases
    - [x] error case
    - [x] add unit tests and update `Config` query
    - [x] add test case for **spa** mode
1. [x] add documentation
1. [x] Refactoring
    - [x] Use [`async` or `defer`](https://discourse.mozilla.org/t/async-v-s-defer/53819/4)?  I think in our case `defer` would work well for us?  (avoid jankiness while hydrating mid load)
      - [x] See if **html-webpack-plugin** can do `async` setting?  (Not sure if `async`/ `defer` will work when serializing though...)
      - [x] page bundles are included as `<script>` tags in index.html - should be `async` too, or removed in **strict** mode?
    - [x] Don't render `*.bundle.js` script tags in **strict** mode
    - [x] Don't render `<lit-redux-router>` in **strict** mode (shaved off 5KB from _index.html_ for Greenwood website!)
1. [x] Rename from **mode** to **optimization**
1. [x] Optimize the 404 page (nice to have, follow up issue) - done
1. [x] Final benchmark / performance report for both modes
    - Strict 
    - SPA
1. [x] Create an issue for tracking getting performance close to 100 for Greenwood / all users - made #411
   -  ~~Would like to look more into why our index bundle is so large or is it as optimized as it can be, for SPA mode.  (maybe split out the webpack runtime?  Might include reviewing the merits of our default babel config too.~~
   -  ~~related issues:~~ #357 , #321, #305, #235
1. [x] Explore an issue for migrating Greenwood website to **strict** mode - #410

### CODE REVIEW

**Comment by thescientist13** [comment]
Here are some initial benchmarks from local testing in Greenwood and my personal website.  Will complete with some stats of current performance in productions

## www.greenhouse.io
### Before
TODO

### After
greenhouse io-ssg-local-network-js
greenhouse io-ssg-local-lighthouse
greenhouse io-ssg-local-network


## Greenwood
TODO

**Comment by thescientist13** [comment]
A couple things that are also interesting to observe is that production is already pretty bad, but none of the things having to do with the size of our JavaScript will fix things, seemingly?
> These suggestions can help your page load faster. They don't directly affect the Performance score.

The issues with LCP, TTI, TBT are seemingly a result of other causes then?

Naturally, strict / ssg mode passes with flying colors as can be seen in the above comment.

For comparison though, my website is doing somewhat better than greenwood production website though
greenhouseio-network
greenhouseio-lighthouse

Interestingly, the Getting Started repo, which is bare bones, fares surprisingly better out of all of them?  (Which I guess is expected, but why such a sharp drop off?)
getting-started-network
getting-started-lighthouse

-----

So perhaps the issues here are related to 
- something specific to our app code that isn't being done in the Getting Started? 
- would be good to see if commenting out some of the bundled code would help improve the score?  (like if bundle size was closer to 100KB?)
- Maybe we should use more `HTMLElement` where possible?

**Comment by hutchgrant** [comment]
* comment out external font from `style/theme.css`
* comment out  analytics, polyfills, markdown plugins from `greenwood.config.js`

In spa mode I noticed an immediate reduction in **Total Blocking Time** when testing lighthouse in mobile mode (where the problem is).  Which resulted in an increase score of performance 67.  Not great but an improvement none the less.

in ssg mode those changes resulted in a performance score of 100 when testing lighting house in mobile mode.

**Comment by hutchgrant** [comment]
nearly a perfect lighthouse score on mobile and desktop. One issue I noticed, our "get started" button is now green again.

**Pull request merged**
