### PR TITLE
ISSUE #124 - refactor chevron svgs by removing them from the shelf component into…

### PR DESCRIPTION
**Pull request by aholtzman**
… a svg component for importing

## Related Issue

https://github.com/ProjectEvergreen/greenwood/issues/124

### CODE REVIEW

**Comment by aholtzman** [comment]
easy enough, just thought it might keep the components from getting to cluttered as we intend to do the same with the social icons.

**Comment by thescientist13** [comment]
> easy enough, just thought it might keep the components from getting to cluttered as we intend to do the same with the social icons.

Good point... maybe something like
```
www/components/icons/
   chevron-down/chevron-dowm.js
   chevron-right/chevron-left.js
```

So at least they are all grouped, but still individual to group individual styles / tests / etc needed on a a case by case basis?

**Comment by aholtzman** [comment]
that makes sense  - TK shortly

**Comment by thescientist13** [comment]
Nice @aholtzman , thanks!!

**Pull request merged**
