### PR TITLE
Fix/issue 432 correct shelf and markdown plugins

### PR DESCRIPTION
**Pull request by hutchgrant**
## Related Issue
#432

## Summary of Changes

* Fix shelf not expanding properly
* Fix page headers not being linked (markdown plugins not being executed in unified.js)
* Fixed `<ol>`
* Fixed missing link icons on headers (order of markdown plugins + merged postcss from release/0.10.0 branch)
* Fixed inline code block highlighting
* brought back our markdown config tests from master
* Fixed linkHeadings not being respected because not using our previous graphql query
* Fixed expanded subitems not linking to the menus page + anchor, rather than page it was initially clicked on

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
Awesome!

Do we know if any of these other known issues are now solved too?   (Maybe will need #453 to gets merged and rebased here?)
1. https://github.com/ProjectEvergreen/greenwood/pull/452#issuecomment-750407404
1. https://github.com/ProjectEvergreen/greenwood/pull/452#pullrequestreview-559284867

Basically just curious if the website now has feature parity with itself or if any other work is needed here to achieve that?

**Comment by thescientist13** [comment]
Oh, additional bonus points.  With this fix, we should be able to re-enable these test cases now?
Screen Shot 2020-12-30 at 10 28 56 AM

**Comment by thescientist13** [comment]
@aholtzman 
In our shift from nested -> un-nested -> back again as temporary work arounds, it seems like I may have put the code through a round of telephone, and little styles (or the markup) need to be put back into place to better reflect what we originally had (which should all work in theory).  Wasn't sure if that's something you could help out with here?  

Examples are in the parent ticket for reference.

The only thing I did want to discuss was the click targets for the shelf.  I think the prior working action was clicking the shelf label controlled the routing _and_ the expand / collapse of sub items.  Not sure how good this is for UX, so I localized the expand / collapse to just the arrow.  Open to suggestions here on how best to approach this interaction.

**Comment by hutchgrant** [comment]
* fixed <ol>
* fixed missing link icons on headers (order of markdown plugins + merged postcss from release/0.10.0 branch)
* fixed inline code block highlighting

**Comment by hutchgrant** [comment]
Should we only allow link icons to be displayed on h2, h3 ?

**Comment by thescientist13** [comment]
> Should we only allow link icons to be displayed on h2, h3 ?

I think it was `<h3>` before, as we used `<h2>` to start every doc page.

**Review by thescientist13 — APPROVED** [review]
Looks good, and not super urgent (nothing we can't resolve as part of #428 ) but when using `yarn serve` pages with the scroll still render a little bit pre scrolled.  (header is cut off)
Screen Shot 2020-12-31 at 12 07 47 PM


Not sure if it's the _index.html_ being shown in the browser URL, e.g. _docs/index.html_ that may be tripping up the scroll or if it's related to just some CSS?  

Other minor thing: If you expand a shelf item and click one of its children, it wont load that section of the docs.  For example go to docs and expand markdown, and go to click one of the sub children.  

Not a big deal on either of these, as the click action of the shelf is something we can tack onto #112 or #428 .

**Comment by thescientist13** [comment]
@hutchgrant 
Before I merge, just want to confirm we think we know what's going on with the header offset issue i'm seeing here? (even after merging prod server url)
https://github.com/ProjectEvergreen/greenwood/pull/459#pullrequestreview-560520742

I can push to another issue but ideally just want to make sure we have an answer for it either way.

**Review by thescientist13 — COMMENTED** [review]
Found that there was a bit of an opportunity to refine the scroll logic.  In production, it looks like `<a>` tags were being passed through the `filter`
Screen Shot 2021-01-20 at 9 41 59 PM

Made a [small tweak](https://github.com/ProjectEvergreen/greenwood/pull/459/commits/96d3ba4c1575bfa2d4d2ae52f631f0bc547539b0) and now everything is groovy 💯

**Pull request merged**
