### PR TITLE
Bug/issue 371 similar query calls invariant error

### LINKED ISSUE #371: similar query calls breaking production build with Invariant Violation 8 error
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
In my [website project](https://github.com/thegreenhouseio/www.thegreenhouse.io/pull/137), I have a [page template](https://github.com/thegreenhouseio/www.thegreenhouse.io/blob/technical/issue-133-markdown-for-blog-posts-bak/src/templates/post-template.js) template that is making its own `query` call.
```js
import { html, LitElement } from 'lit-element';
import client from '@greenwood/cli/data/client';
import gql from 'graphql-tag';

import '../components/blog-post/blog-post';
import '../components/footer/footer';
import '../components/header/header';
import '../components/navigation/navigation';
import pageCss from '../styles/page.css';
import '../styles/theme.css';

MDIMPORT;

class PostTemplate extends LitElement {
  ...

  async connectedCallback() {
    super.connectedCallback();
    let route = window.location.pathname;
    const response = await client.query({
      query: gql`query {
        graph {
          title,
          link,
          data {
            date,
            image
          }
        }
      }`
    });

    ...
  }

  ...
}

customElements.define('page-template', PostTemplate);
```

Results in an ApolloClient error
```
index.c10096742db3b816782b.bundle.js:1 Uncaught (in promise) Invariant Violation: Invariant Violation: 8 (see https://github.com/apollographql/invariant-packages)
    at new t (http://localhost:8000/index.c10096742db3b816782b.bundle.js:1:17113)
    at l (http://localhost:8000/index.c10096742db3b816782b.bundle.js:1:17334)
    at R (http://localhost:8000/index.c10096742db3b816782b.bundle.js:1:10323)
    at L (http://localhost:8000/index.c10096742db3b816782b.bundle.js:1:13986)
    at t.transformDocument (http://localhost:8000/index.c10096742db3b816782b.bundle.js:98:67607)
    at t.read (http://localhost:8000/index.c10096742db3b816782b.bundle.js:98:65761)
    at t.e.readQuery (http://localhost:8000/index.c10096742db3b816782b.bundle.js:98:45766)
    at http://localhost:8000/index.c10096742db3b816782b.bundle.js:98:72246
```

Screen Shot 2020-06-16 at 8 38 43 PM

## Details
What I think correlation here is that since app-template is also making a `query` call for the graph, and this page template an adapted version of it, when logging _cache.json_, it looks like there are _two_ entries for the graph, one per call.  
Screen Shot 2020-06-16 at 8 40 56 PM

Since it only happens in production, this is likely an issue with our [mock Apollo client](https://spectrum.chat/apollo/apollo-client/optimistic-response-failed-with-invariant-violation-8~9995b7e0-4cdd-42d1-9a50-2b3983079d2d).

### PR DESCRIPTION
**Pull request by thescientist13**
## Related Issue
resolves #371 

1. Created a common utility that will generate a unique hash per query, that can in turn be used to write / read cache file paths in _cache.js_ and _client.js_, respectively
1. Added unit tests and test cases, observed #386 that may result in intermittent test failures on this PR perhaps
1. Removed _cache.json_, left `window.__APOLLO_STATE__`, cleaned up deps.  
    - This effectively invalidates #349 at this point, IMO
    - Would also take care of #317 too then?

~~**Note**: You can test on the home page now and see multiple `query` calls now returning.   However, do keep in mind that pages with a menu will break right now until I add support for variables.  (right now both `menu` queries are using the same keys and so filenames are not unique)~~
Screen Shot 2020-07-08 at 10 21 37 PM

## TODOs
1. [x] Add support for variables (to fix pages with `menu` queries)
1. [x] Add a test case
1. [x] remove `deepmerge` dependency / unified _cache.json_ in **serialize** lifecycle.  All _-cache.json_ files can now stay at the root as well
1. [x] return an actual hash
1. [x] Perf comparison - need to swap out with something other than `crypto`, much too large!
1. [x] remove `console` logs / example in _home-template.js_

### CODE REVIEW

**Comment by hutchgrant** [comment]
Does this also partially address #317 with deepmerge gone?

**Comment by thescientist13** [comment]
> Does this also partially address #317 with deepmerge gone

I believe so!

**Comment by hutchgrant** [comment]
Excellent a 2 for 1.  This provide valuable information now on why how we're overfetching. I noticed we're fetching side menu cache query 3 times, navigation twice, greenwood config once, and graph once.  Note the graph and config queries are in the `app-template.js` whereas the others are in the `page-template.js`.  I haven't reviewed this yet just cursory look at the results and it looks promising.

**Comment by thescientist13** [comment]
OK, did some quick performance checks and looks like i need to swap out `crypto` with [something else](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa), or figure out a way to slim it down.  It almost doubles the bundle size!  Nothing fancy, if we even want to obfuscate the name?  🤷‍♂️ 

With
```
-rw-r--r--   1 owenbuckley  staff  551585 Jul 14 09:53 index.c69a6e52fffa6a3bec0f.bundle.js
```

Without
```
-rw-r--r--   1 owenbuckley  staff  244633 Jul 14 09:56 index.8b04ed729af8e894acb4.bundle.js
```

Not a big deal, maybe can use btoa inxtead.

**Comment by hutchgrant** [comment]
Just use https://www.npmjs.com/package/md5  I just tested it on your build its much smaller.

**Comment by thescientist13** [comment]
Giving [this solution](https://gist.github.com/hyamamoto/fd435505d29ebfa3d9716fd2be8d42f0#gistcomment-2775538) a try, with some additional tweaks, using `Math.abs` to ensure unsigned values (the third test for variables was returning a negative value) and then cast `.toString()`.

**Pull request merged**
