### PR TITLE
fix: remove scrollbar

### LINKED ISSUE #830: greenwood website page style is displaying scroll bars
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
The greenwood site is displaying scroll bars next to the content.

image

## Details

The page style needs to have `overflow: scroll` removed

### PR DESCRIPTION
**Pull request by hutchgrant**
## Related Issue
Resolves #830

## Summary of Changes

removes `overflow:scroll`

### CODE REVIEW

**Review by thescientist13 — APPROVED** [review]
I don't see the scrollbar before but everything still looks OK, so take my ✅ with a grain of YMMV 🙃

**Review by thescientist13 — COMMENTED** [review]
I thought this issue seemed familiar.  Looks like we had attempted a fix for this before, interestingly enough - https://github.com/ProjectEvergreen/greenwood/pull/831

@hutchgrant 
Though I'm not opposed to merging given it is such a small change, can you confirm what version you see in the footer?  (just to ensure no caching issues?)
Screen Shot 2021-12-21 at 12 44 54 PM

To me it looks the same before / after so I hesitate to be the final judge on this just yet.  👉 🥺 👈

**Comment by hutchgrant** [comment]
image

@thescientist13  this is present on current version and upon checking the PR you referenced and its preview on netlify, it also was never fixed as overflow:scroll was still present. 

image

**Comment by hutchgrant** [comment]
Of course, my changes in this PR do in fact correctly fix the problem:

image

**Comment by hutchgrant** [comment]
Further tests on browser stack, I did not see the scrollbars on mac chrome v96 or safari.

I did however see this on windows 11 chrome v96.  It cancelled my testing shortly after.

**Comment by thescientist13** [comment]
Awesome, thanks for the extra context, plus the link you shared in Slack was super helpful and actually helped jog my memory on a similar issue I also ran into before here - https://github.com/thescientist13/greenwood-starter-presentation/issues/50.

I fired up my Windows VM and yup, sure enough, there they were.  😢 
Screen Shot 2021-12-27 at 12 44 23 PM

But thankfully switching to your branch fixed them!  🙌
Screen Shot 2021-12-27 at 12 47 59 PM

It's a festivus miracle!

**Pull request merged**
