### PR TITLE
testing refactoring for build matrix

### LINKED ISSUE #180: set minimum node version in package.json
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
_package.json_ can support identifying a minimum version of Node required when installing the project, e.g.
```json
"engines": {
  "node": ">= 6.9.0 < 13.0.0"
},
```

## Details
Would be good to set this to help provide clear feedback to users at install time.  Recommendation would be to go with the current LTS 10.x, though I think 12 as LTS may be coming soon?

### PR DESCRIPTION
**Pull request by thescientist13**
## Related Issue
resolves #180 

## Summary of Changes
1. Refactor GitHub Actions to appropriately take advantage of Node Matrix based on [this example](https://github.com/ianwalter/puppeteer). 🤞

### CODE REVIEW

**Comment by thescientist13** [comment]
Interesting.  Noticed an odd failure for a spec, which had been refactored as part of #259 
https://github.com/ProjectEvergreen/greenwood/runs/357556860
```
 331 passing (3m)
  1 failing

  1) Build Greenwood With: 
       Empty Configuration and Default Workspace
         "before all" hook in "Empty Configuration and Default Workspace":
     Error: the string "TypeError: this.browser.newPage is not a function\n" was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

But even removing `async` didn't get it working.  Not sure why the `puppeteer` call is failing just for that one spec?  🤔

**Comment by hutchgrant** [comment]
I'm going out on a limb here but here's my hypothesis.

`this.browser` was not initialized because in our puppeteer render library we're call async init() from constructor. So this.browser, within init() doesn't execute in time before the rest of the thread. 

*lib/browser.js*
```js
  constructor() {
    this.browser = {}, this.renderer = {};
    this.init();
  }
  async init() {
    this.browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox']
    });
    // this.renderer = new Renderer(this.browser);
  }

```

**Comment by thescientist13** [comment]
> I believe this is the result of the merge between the 2 puppeteer render libraries we were previously using

good call, will look back to see if this is the issue, but either way your point about `async` usage here seems a little clunky, so a tweak here would seem worthwhile either way.

**Comment by thescientist13** [comment]
Good call @hutchgrant , looks like our matrix is running tests successfully now!  👏 👏 👏 

Gonna start calling you the Async King 👑

**Pull request merged**
