### PR TITLE
resolve website issue 143, remove index dependence for the shelf rend…

### PR DESCRIPTION
**Pull request by aholtzman**
resolve website issue 143, remove index dependence for the shelf render from the json data.

## Related Issue

https://github.com/ProjectEvergreen/greenwood/issues/143

### CODE REVIEW

**Comment by aholtzman** [comment]
Yeah @thescientist13 I use this technique all the time, it does not use an index or id number from the json (if they are there they are ignored). We can confirm it by removing it from the json and printing the index out...

**Comment by thescientist13** [comment]
I think I see what you mean now, clever!   I wasn't sure if the `index` was part of some sort of sorting logic.  @hutchgrant can you confirm what `index` is used for?

**Comment by thescientist13** [comment]
@aholtzman 
Can you edit all those _.json_ files too?  If `index` isn't being used by any business logic for sorting the shelf items in the component itself, and just for this output, then we should remove it altogether.  (including in the _.json_ files too)

**Comment by aholtzman** [comment]
will do @thescientist13

**Comment by hutchgrant** [comment]
I'm noticing another issue with shelf, I don't think it's related to this PR and I don't know when it was introduced. The shelf will open and collapse, but refuses to open again.

**Pull request merged**
