### PR TITLE
Change Webcomponents Logo

### LINKED ISSUE #1057: update logo for Web Components at the bottom of the website home page
## Type of Change
website

## Summary
At the bottom of the home page is a logo for Web Components in the left tile.
https://www.greenwoodjs.io/
Screen Shot 2023-02-06 at 9 31 42 PM

## Details
In the WebComponents Working Group, pGoogle / the Web Components SF group](https://github.com/w3c/webcomponents-cg/issues/4#issuecomment-1150073722) have offered up a new logo that the community has started gaining consensus on, so thought it would be good to get it updated on our website

Logo1
Logo2

### PR DESCRIPTION
**Pull request by loki1205**
## Related Issue
  Resolves #1057 

## Summary of Changes
1. [x] Added Webcomponents Logo
2. [x] Removed old webcomponent logo
3. [x] Updated index.html with the logo file

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
Thanks for this @loki1205 and looks really good in the deploy preview!

My only thought is to see if there's any room to compress the image at all (assuming the quality doesn't suffer too much).  You can play around with [squoosh.app](https://squoosh.app/) a bit and see if there are any savings worth taking advantage of,  just to help bring the image size (KB) down at all.

**Comment by loki1205** [comment]
done please check it and let me know.

**Review by thescientist13 — APPROVED** [review]
Awesome, looks good to me!  Will see if anyone else on the team has any thoughts but otherwise should be good to merge soon.

**Comment by thescientist13** [comment]
Thank you!

**Pull request merged**
